In [1]:
import sys
# script specific requirement in readme
sys.path.insert(0,"/home/keshav/courses/master_thesis/Graph-Transformer/U2GNN_pytorch/log_uniform")
from U2GNN_pytorch import util
from U2GNN_pytorch import train_utils

In [2]:
graph, num_classes = util.load_data("IMDBBINARY",True)

loading data
dataset file chosen is /home/keshav/courses/master_thesis/Graph-Transformer/dataset/IMDBBINARY/IMDBBINARY.txt
# classes: 2
# maximum node tag: 65
# data: 1000


In [3]:
(graph[1].edge_mat.shape)

(2, 256)

In [4]:
vars(graph[1])

{'label': 0,
 'g': <networkx.classes.graph.Graph at 0x7f9d9ac64c18>,
 'node_tags': [4,
  4,
  4,
  31,
  31,
  4,
  4,
  4,
  10,
  10,
  10,
  13,
  10,
  10,
  10,
  10,
  10,
  4,
  4,
  4,
  5,
  5,
  5,
  5,
  6,
  6,
  6,
  6,
  6,
  5,
  5,
  5],
 'neighbors': [[6, 7, 14, 23],
  [14, 23, 2, 27],
  [14, 23, 1, 27],
  [14, 23, 4, 5, 13, 20, 21, 26, 28, 29],
  [14, 23, 3, 5, 13, 20, 21, 26, 28, 29],
  [14, 23, 3, 4, 13, 20, 21, 26, 28, 29],
  [0, 7, 14, 23],
  [0, 6, 14, 23],
  [14, 23, 9, 30],
  [14, 23, 8, 30],
  [14, 23, 17, 18, 22],
  [14, 23, 12, 16, 24, 25],
  [14, 23, 11, 16, 24, 25],
  [14, 23, 3, 4, 5, 15, 19, 20, 21, 26, 28, 29, 31],
  [0,
   6,
   7,
   1,
   2,
   3,
   4,
   5,
   8,
   9,
   10,
   11,
   12,
   13,
   15,
   16,
   17,
   18,
   19,
   20,
   21,
   22,
   23,
   24,
   25,
   26,
   27,
   28,
   29,
   30,
   31],
  [14, 23, 13, 19, 31],
  [14, 23, 11, 12, 24, 25],
  [14, 23, 10, 18, 22],
  [14, 23, 10, 17, 22],
  [14, 23, 13, 15, 31],
  [14, 23, 3

In [5]:
args={'device':'cuda'}
args['batch_size']=4
args['dataset']="IMDBBINARY"
args['num_epochs']=50
args['num_neighbors']=16
args= train_utils.Namespace(**args)
graph_pool = train_utils.get_graphpool(graph,args)

In [6]:
graph_pool.shape

torch.Size([1000, 19773])

In [7]:
len(graph)

1000

In [8]:
print(list(int(indice) for indice in graph_pool._indices()[0]))


[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 1

In [9]:
graph_indices = graph_pool._indices()[0]
batch_nodes = train_utils.Batch_Loader(graph,graph_indices,args)

In [10]:
vars(batch_nodes())

TypeError: vars() argument must have __dict__ attribute

In [11]:
import numpy as np
selected_idx = np.random.permutation(len(graph))[:args.batch_size]


In [12]:
selected_idx

array([468, 319, 673, 601])

In [13]:
X_concat, input_x, input_y = train_utils.get_batch_data(graph, graph_indices, selected_idx, args)

In [69]:
def get_Adj_matrix(batch_graph):
    edge_mat_list = []
    start_idx = [0]
    for i, graph in enumerate(batch_graph):
        
        start_idx.append(start_idx[i] + len(graph.g))
        edge_mat_list.append(graph.edge_mat + start_idx[i])
        print(edge_mat_list)

    Adj_block_idx = np.concatenate(edge_mat_list, 1)
    # Adj_block_elem = np.ones(Adj_block_idx.shape[1])
    print(Adj_block_idx)
    Adj_block_idx_row = Adj_block_idx[0,:]
    Adj_block_idx_cl = Adj_block_idx[1,:]

    return Adj_block_idx_row, Adj_block_idx_cl

In [70]:
get_Adj_matrix([graph[0],graph[0]])

[array([[ 0,  0,  0,  0,  0,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
         2,  2,  2,  2,  2,  2,  2,  4,  4,  4,  5,  5,  9,  1,  1,  1,
         1,  1,  1,  1,  6,  6,  6,  6,  6,  6,  6,  6,  6,  8,  8,  8,
         8,  8, 12, 12, 12, 12, 12, 12, 12, 14, 14, 14, 17, 17, 18, 19,
        19, 19, 19,  3,  3,  7,  7, 11, 13,  2,  4,  5,  9, 10,  1,  3,
         4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
         5,  9, 10,  9, 10, 10,  6,  8, 12, 14, 17, 18, 19,  3,  8, 11,
        12, 14, 16, 17, 18, 19, 12, 14, 17, 18, 19,  3, 11, 14, 16, 17,
        18, 19, 17, 18, 19, 18, 19, 19,  3, 11, 15, 16, 11, 16, 13, 15,
        16, 15],
       [ 2,  4,  5,  9, 10,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,
        13, 14, 15, 16, 17, 18, 19,  5,  9, 10,  9, 10, 10,  6,  8, 12,
        14, 17, 18, 19,  3,  8, 11, 12, 14, 16, 17, 18, 19, 12, 14, 17,
        18, 19,  3, 11, 14, 16, 17, 18, 19, 17, 18, 19, 18, 19, 19,  3,
        11, 15, 16, 11, 16, 13, 15, 16, 15,  0

(array([ 0,  0,  0,  0,  0,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
         2,  2,  2,  2,  2,  2,  4,  4,  4,  5,  5,  9,  1,  1,  1,  1,  1,
         1,  1,  6,  6,  6,  6,  6,  6,  6,  6,  6,  8,  8,  8,  8,  8, 12,
        12, 12, 12, 12, 12, 12, 14, 14, 14, 17, 17, 18, 19, 19, 19, 19,  3,
         3,  7,  7, 11, 13,  2,  4,  5,  9, 10,  1,  3,  4,  5,  6,  7,  8,
         9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  5,  9, 10,  9, 10, 10,
         6,  8, 12, 14, 17, 18, 19,  3,  8, 11, 12, 14, 16, 17, 18, 19, 12,
        14, 17, 18, 19,  3, 11, 14, 16, 17, 18, 19, 17, 18, 19, 18, 19, 19,
         3, 11, 15, 16, 11, 16, 13, 15, 16, 15, 20, 20, 20, 20, 20, 22, 22,
        22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 24,
        24, 24, 25, 25, 29, 21, 21, 21, 21, 21, 21, 21, 26, 26, 26, 26, 26,
        26, 26, 26, 26, 28, 28, 28, 28, 28, 32, 32, 32, 32, 32, 32, 32, 34,
        34, 34, 37, 37, 38, 39, 39, 39, 39, 23, 23, 27, 27, 31, 33, 22, 24,
        25, 

In [72]:
input_x.shape

torch.Size([57, 17])

In [74]:
input_y

tensor([ 8297,  8298,  8299,  8300,  8301,  8302,  8303,  8304,  8305,  8306,
         8307,  8308,  8309,  8310,  8311, 12117, 12118, 12119, 12120, 12121,
        12122, 12123, 12124, 12125, 12126, 12127, 12128, 12129, 12130, 11719,
        11720, 11721, 11722, 11723, 11724, 11725, 11726, 11727, 11728, 11729,
        11730, 15342, 15343, 15344, 15345, 15346, 15347, 15348, 15349, 15350,
        15351, 15352, 15353, 15354, 15355, 15356, 15357], device='cuda:0')

In [75]:
graph_indices

tensor([  0,   0,   0,  ..., 999, 999, 999], device='cuda:0')

In [76]:
input_x

tensor([[ 0,  3,  7,  5,  9, 10, 14, 10,  2, 11,  1, 10,  3,  4,  3,  7,  1],
        [ 1,  3,  0,  2,  8,  0,  0,  8,  0,  8,  2,  2,  4,  0,  8,  0,  0],
        [ 2,  1,  4,  3,  3,  3,  4,  4,  3,  1,  8,  4,  1,  8,  1,  4,  4],
        [ 3,  2,  4,  2,  2,  1,  0,  5,  4,  1,  0,  1,  4,  5,  8,  0,  1],
        [ 4,  0,  2,  2,  3,  3,  2,  3,  3,  1,  0,  1,  2,  8,  2,  1,  3],
        [ 5,  0,  3,  7,  3, 11, 14, 14, 12, 13,  3,  7,  9,  7,  9, 13, 12],
        [ 6, 13,  9, 12, 14, 14,  0, 13,  0,  5,  5, 13,  0,  0, 10,  0, 12],
        [ 7, 14,  6, 11,  5,  0,  6,  5, 10, 10, 10,  0, 12,  6,  5, 12,  6],
        [ 8,  4,  4,  2,  0,  1,  1,  4,  3,  2,  3,  0,  3,  1,  1,  2,  4],
        [ 9, 10,  0, 12,  6, 10, 14, 12,  0, 14,  7,  0, 14,  7, 13, 14,  0],
        [10,  7,  7, 13,  6, 12,  6,  5,  0,  5,  0,  6, 11,  6, 12,  6,  7],
        [11, 10,  0,  6,  7,  7,  0,  9,  7, 14, 12, 14,  9,  6, 14, 13,  5],
        [12, 13,  6, 10,  7,  5, 11,  6,  7,  9,  6, 13, 14,  9,

In [81]:
import torch.nn.functional as F
import torch

In [102]:
input_this=F.embedding(input_x, X_concat).to('cuda')
print(input_this.shape)

torch.Size([57, 17, 65])


In [105]:
encoder_layer = torch.nn.TransformerEncoderLayer(d_model=65, nhead=1)
transformer_encoder = torch.nn.TransformerEncoder(encoder_layer, num_layers=6)
src = torch.rand(57, 17, 65)
out = transformer_encoder(src)

In [106]:
out.shape

torch.Size([57, 17, 65])

In [93]:
a = torch.arange(20).reshape(5,2,2)
a.shape

torch.Size([5, 2, 2])

In [109]:
torch.split(out, split_size_or_sections=1, dim=1)[0].squeeze(dim=1).shape

torch.Size([57, 65])

In [14]:
input_y

tensor([ 9479,  9480,  9481,  9482,  9483,  9484,  9485,  9486,  9487,  9488,
         9489,  9490,  9491,  9492,  9493,  9494,  9495,  6405,  6406,  6407,
         6408,  6409,  6410,  6411,  6412,  6413,  6414,  6415,  6416,  6417,
         6418, 13403, 13404, 13405, 13406, 13407, 13408, 13409, 13410, 13411,
        13412, 13413, 13414, 13415, 13416, 13417, 13418, 13419, 13420, 13421,
        13422, 13423, 13424, 13425, 13426, 13427, 13428, 13429, 11959, 11960,
        11961, 11962, 11963, 11964, 11965, 11966, 11967, 11968, 11969, 11970,
        11971], device='cuda:0')

In [17]:
vocab_size=graph_pool.size()[1]
print(vocab_size)

19773


In [20]:
from U2GNN_pytorch.sampled_softmax import  *



In [21]:
ss= SampledSoftmax(vocab_size, 200, 65, 'cuda')

In [22]:
from log_uniform import LogUniformSampler

In [23]:
sampler = LogUniformSampler(vocab_size)

In [24]:
samples = sampler.sample(200, input_y.data.cpu().numpy())

In [27]:
len(samples[0])

200

In [32]:
len(samples[1])

71

In [33]:
len(input_y)

71

In [34]:
samples[1]

[0.0027685542590916157,
 0.0027682625222951174,
 0.0027679710183292627,
 0.002767679514363408,
 0.0027673880103975534,
 0.0027670967392623425,
 0.002766805700957775,
 0.002766514429822564,
 0.002766223158687353,
 0.002765932120382786,
 0.002765640849247575,
 0.002765350043773651,
 0.0027650592382997274,
 0.00276476819999516,
 0.0027644773945212364,
 0.0027641865890473127,
 0.0027638960164040327,
 0.004094264004379511,
 0.004093626048415899,
 0.004092989023774862,
 0.004092351533472538,
 0.004091714508831501,
 0.004091077484190464,
 0.004090440925210714,
 0.004089804366230965,
 0.004089168272912502,
 0.00408853217959404,
 0.004087896551936865,
 0.0040872604586184025,
 0.004086625296622515,
 0.00408598966896534,
 0.0019588859286159277,
 0.0019587399438023567,
 0.0019585939589887857,
 0.0019584479741752148,
 0.001958301989361644,
 0.0019581562373787165,
 0.0019580102525651455,
 0.001957864500582218,
 0.001957718515768647,
 0.00195757276378572,
 0.0019574270118027925,
 0.001957281259819865

In [36]:
len(samples[2])

200

In [38]:
samples[0]

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 514,
 8,
 10,
 11,
 12,
 3085,
 13,
 15,
 16,
 17,
 4621,
 18,
 14,
 7701,
 22,
 534,
 24,
 23,
 4117,
 27,
 28,
 25,
 29,
 31,
 32,
 8227,
 37,
 39,
 40,
 42,
 5675,
 45,
 16434,
 51,
 52,
 54,
 5175,
 56,
 57,
 59,
 60,
 61,
 62,
 64,
 5698,
 579,
 1091,
 67,
 70,
 73,
 75,
 587,
 79,
 80,
 81,
 593,
 19026,
 15957,
 6743,
 88,
 93,
 102,
 1130,
 106,
 21,
 8813,
 109,
 6770,
 16498,
 5237,
 13431,
 119,
 121,
 2171,
 1661,
 127,
 647,
 135,
 648,
 144,
 145,
 147,
 1171,
 148,
 661,
 7318,
 150,
 1178,
 4766,
 160,
 161,
 1187,
 165,
 4264,
 172,
 175,
 10417,
 15538,
 179,
 8884,
 19638,
 1208,
 9917,
 192,
 10433,
 19653,
 1734,
 198,
 202,
 210,
 211,
 213,
 214,
 6370,
 2789,
 4326,
 742,
 4842,
 236,
 2286,
 239,
 1778,
 15092,
 1270,
 1272,
 2300,
 254,
 255,
 769,
 17154,
 261,
 9477,
 16648,
 18189,
 273,
 287,
 1826,
 2851,
 1315,
 10535,
 1840,
 2365,
 318,
 15681,
 1351,
 12108,
 2390,
 2395,
 16736,
 1892,
 19301,
 364,
 8047,
 369,
 8050